title: Frank Li
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/monday" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Shanchuan(Frank) Li
tagline: Business Data Scientist
about-description: # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: frank.li@emory.edu # Add your Email address
phone: 404 232 9370 # Add your Phone number
website: shanchuanli@qq.com
linkedin: linkedin.com/in/shanchuan-li/ # Add your Linkedin handle
github: github.com/shanchuan-li # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle
# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
